language: python
sudo: required

python:
  - 2.7

services:
    - rabbitmq

env:
  - TOX_ENV=docs
  - TOX_ENV=flake8
  - TOX_ENV=py27
  - TOX_ENV=py26

install:
  - pip install tox

script:
  - tox -e $TOX_ENV