#########
# Copyright (c) 2015 GigaSpaces Technologies Ltd. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
#  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  * See the License for the specific language governing permissions and
#  * limitations under the License.


CLOUDIFY_DAEMON_QUEUE = 'CLOUDIFY_DAEMON_QUEUE'
CLOUDIFY_DAEMON_EXTRA_ENV = 'CLOUDIFY_DAEMON_EXTRA_ENV'
CLOUDIFY_DAEMON_WORKDIR = 'CLOUDIFY_DAEMON_WORKDIR'
CLOUDIFY_DAEMON_USER = 'CLOUDIFY_DAEMON_USER'
CLOUDIFY_DAEMON_PROCESS_MANAGEMENT = 'CLOUDIFY_DAEMON_PROCESS_MANAGEMENT'
CLOUDIFY_DAEMON_NAME = 'CLOUDIFY_DAEMON_NAME'
CLOUDIFY_DAEMON_MIN_WORKERS = 'CLOUDIFY_DAEMON_MIN_WORKERS'
CLOUDIFY_DAEMON_MAX_WORKERS = 'CLOUDIFY_DAEMON_MAX_WORKERS'
CLOUDIFY_BROKER_IP = 'CLOUDIFY_BROKER_IP'
CLOUDIFY_BROKER_PORT = 'CLOUDIFY_BROKER_PORT'
CLOUDIFY_REST_HOST = 'REST_HOST'
CLOUDIFY_REST_PORT = 'REST_PORT'
CLOUDIFY_LOCAL_REST_CERT_PATH = 'LOCAL_REST_CERT_FILE'
CLOUDIFY_DAEMON_LOG_LEVEL = 'CLOUDIFY_DAEMON_LOG_LEVEL'
CLOUDIFY_DAEMON_PID_FILE = 'CLOUDIFY_DAEMON_PID_FILE'
CLOUDIFY_DAEMON_LOG_FILE = 'CLOUDIFY_DAEMON_LOG_FILE'
CLOUDIFY_DAEMON_HOST = 'CLOUDIFY_DAEMON_HOST'
CLOUDIFY_DAEMON_DEPLOYMENT_ID = 'CLOUDIFY_DAEMON_DEPLOYMENT_ID'
CLOUDIFY_BROKER_USER = 'CLOUDIFY_BROKER_USER'
CLOUDIFY_BROKER_PASS = 'CLOUDIFY_BROKER_PASS'
CLOUDIFY_BROKER_SSL_ENABLED = 'CLOUDIFY_BROKER_SSL_ENABLED'
CLOUDIFY_BROKER_SSL_CERT = 'CLOUDIFY_BROKER_SSL_CERT'
CLOUDIFY_BROKER_GET_SETTINGS_FROM_MANAGER = \
    'CLOUDIFY_BROKER_GET_SETTINGS_FROM_MANAGER'
CLOUDIFY_BYPASS_MAINTENANCE_MODE = 'CLOUDIFY_BYPASS_MAINTENANCE_MODE'
CLOUDIFY_BROKER_SSL_CERT_PATH = 'BROKER_SSL_CERT_PATH'
CLOUDIFY_REST_USERNAME = 'CLOUDIFY_REST_USERNAME'
CLOUDIFY_REST_PASSWORD = 'CLOUDIFY_REST_PASSWORD'
CLOUDIFY_REST_TOKEN = 'CLOUDIFY_REST_TOKEN'
CLOUDIFY_REST_TENANT = 'CLOUDIFY_REST_TENANT'
