apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:4.11.2-2
    resources:
      limits:
        cpu: 0.3
        memory: 256Mi
  - name: py311
    image: 263721492972.dkr.ecr.eu-west-1.amazonaws.com/cloudify-python3.11
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    resources:
      limits:
        cpu: 1
        memory: 1Gi
  - name: rpmbuild
    image: 263721492972.dkr.ecr.eu-west-1.amazonaws.com/cloudify-rpmbuild-rh8
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    resources:
      limits:
        cpu: 1
        memory: 1Gi
  - name: awscli
    image: amazon/aws-cli
    command:
    - cat
    tty: true
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot-xlarge
