apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:4.3-4
    resources:
      limits:
        cpu: 0.3
        memory: 256Mi
  - name: py27
    image: circleci/python:2.7
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    resources:
      requests:
        cpu: 1
        memory: 3Gi
      limits:
        cpu: 1
        memory: 3Gi
  - name: py36
    image: 263721492972.dkr.ecr.eu-west-1.amazonaws.com/cloudify-python3.6
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    resources:
      limits:
        cpu: 1
        memory: 1Gi
  - name: centos7
    image: centos:7
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    resources:
      limits:
        cpu: 0.5
        memory: 512Mi
  - name: rpmbuild
    image: 263721492972.dkr.ecr.eu-west-1.amazonaws.com/cloudify-rpmbuild
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    resources:
      limits:
        cpu: 0.3
        memory: 256Mi
  - name: awscli
    image: amazon/aws-cli
    command:
    - cat
    tty: true
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot-xlarge
