apiVersion: v1
kind: Pod
spec:
  containers:
  - name: py36
    image: circleci/python:3.6
    resources:
      requests:
        cpu: 1
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: py27
    image: circleci/python:2.7
    resources:
      requests:
        cpu: 1
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: rabbitmq374
    image: rabbitmq:3.7.4
  nodeSelector:
    instance-type: spot